"""Add database indexes and optimistic locking for performance optimization

Revision ID: 9c5a22028615
Revises: 
Create Date: 2025-09-10 09:12:00.359939

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c5a22028615'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendance_records', sa.Column('version', sa.Integer(), nullable=False, server_default=sa.text('1')))
    op.create_index('idx_attendance_session_checkin', 'attendance_records', ['class_session_id', 'check_in_time'], unique=False)
    op.create_index('idx_attendance_session_student', 'attendance_records', ['class_session_id', 'student_id'], unique=False)
    op.create_index('idx_attendance_student_created', 'attendance_records', ['student_id', 'created_at'], unique=False)
    # Note: Unique constraint removed due to potential existing duplicate data
    # Will be added in a separate migration after data cleanup
    # op.create_index('idx_attendance_unique_session_student', 'attendance_records', ['class_session_id', 'student_id'], unique=True)
    op.alter_column('class_sessions', 'status',
               existing_type=sa.VARCHAR(length=7),
               type_=sa.String(length=10),
               existing_nullable=True)
    op.create_index('idx_class_session_class_created', 'class_sessions', ['class_id', 'created_at'], unique=False)
    op.create_index('idx_class_session_start_time', 'class_sessions', ['start_time'], unique=False)
    op.create_index('idx_class_session_status_time', 'class_sessions', ['status', 'start_time', 'end_time'], unique=False)
    op.create_index('idx_class_session_teacher_status', 'class_sessions', ['teacher_id', 'status'], unique=False)
    op.create_index('idx_class_sis_id', 'classes', ['sis_class_id'], unique=False)
    op.create_index('idx_class_teacher_created', 'classes', ['teacher_id', 'created_at'], unique=False)
    op.create_index('idx_enrollment_class_active', 'student_enrollments', ['class_id', 'is_active'], unique=False)
    op.create_index('idx_enrollment_sis_id', 'student_enrollments', ['sis_enrollment_id'], unique=False)
    op.create_index('idx_enrollment_student_active', 'student_enrollments', ['student_id', 'is_active'], unique=False)
    op.create_index('idx_enrollment_unique_student_class', 'student_enrollments', ['student_id', 'class_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_enrollment_unique_student_class', table_name='student_enrollments')
    op.drop_index('idx_enrollment_student_active', table_name='student_enrollments')
    op.drop_index('idx_enrollment_sis_id', table_name='student_enrollments')
    op.drop_index('idx_enrollment_class_active', table_name='student_enrollments')
    op.drop_index('idx_class_teacher_created', table_name='classes')
    op.drop_index('idx_class_sis_id', table_name='classes')
    op.drop_index('idx_class_session_teacher_status', table_name='class_sessions')
    op.drop_index('idx_class_session_status_time', table_name='class_sessions')
    op.drop_index('idx_class_session_start_time', table_name='class_sessions')
    op.drop_index('idx_class_session_class_created', table_name='class_sessions')
    op.alter_column('class_sessions', 'status',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=7),
               existing_nullable=True)
    # op.drop_index('idx_attendance_unique_session_student', table_name='attendance_records')
    op.drop_index('idx_attendance_student_created', table_name='attendance_records')
    op.drop_index('idx_attendance_session_student', table_name='attendance_records')
    op.drop_index('idx_attendance_session_checkin', table_name='attendance_records')
    op.drop_column('attendance_records', 'version')
    # ### end Alembic commands ###
